### ISSUE TITLE
Keep current version and reload

### ISSUE THREAD

**Issue by kankaristo** [lwblackledge/file-watcher#1]
Thanks for a great package! I was surprised Atom doesn't have this feature by default, as it can destroy changes made outside of Atom...

However, it would be nice to be able to keep Atom's current version before loading the changed on-disk version of the file.

This could be done by either saving a backup version or (preferably) open a new tab with Atom's version of the file, before reloading the on-disk version.

**Comment by lwblackledge** [comment]
Hi @kankaristo thanks for trying this out.

I believe that this is already possible if you select **Ignore** on the prompt that appears if you have local changes. If you select **Ignore** I do not reload the file from disk. You are then able to save over the disk changes from atom, or save it as a separate file as normal.

Is this not working for you?

**Comment by kankaristo** [comment]
Yes, that's working. My description is a bit convoluted, sorry about that. :blush:

I meant that it would be nice to open the 2 different versions into separate tabs automatically. So the dialog would have 3 options: "Ignore", "Open both", "Reload (overwrite buffer)".

This way you could compare the 2 versions side by side, without having to save a "temporary" version to a second file.

**Comment by lwblackledge** [comment]
Ah I see what you mean. That sounds like a good feature, I'll work it into the next release..

**Comment by lwblackledge** [comment]
Added in version 0.3.0

**Comment by kankaristo** [comment]
Fantastic! :+1:

A small improvement; set the grammar (syntax highlighting, autocomplete, etc.) for the unsaved file:

``` CoffeeScript
 confirmReload: ->
     currPath = @editor.getPath()
     currEncoding = @editor.getBuffer()?.encoding || 'utf8'
+    currGrammar = @editor.getGrammar()

     choice = atom.confirm
       message: path.basename(currPath) + ' has changed on disk.'
       buttons: ['Reload', 'Compare', 'Ignore']

     return if choice is 2

     if choice is 0
       @editor.getBuffer()?.reload()
       return

     compPromise = atom.workspace.open null,
       split: 'right'

     compPromise.then (ed) ->
       ed.insertText fs.readFileSync(currPath, encoding: currEncoding)
+      ed.setGrammar currGrammar
```

**Comment by lwblackledge** [comment]
Nice! :heavy_check_mark:
Added, patched and credited.
