### ISSUE TITLE
activate split diff

### ISSUE THREAD

**Issue by benoitcerrina** [lwblackledge/file-watcher#15]
Hello,
I like this package a lot thank you.
One thing which is unfortunate is when you use the compare option there is no highlighting of diffs.
On my installation I have fixed that by installing the split-diff package and triggering it when the compare happens.

It is a one line change

```
  atom.commands.dispatch(document.querySelector('atom-text-editor'), 'split-diff:toggle')
```

added after line 80 of file-watcher.coffee

It would obviously be better if a service api existed on split-diff but in the meantime I think this would be a worthwile improvement

**Comment by lwblackledge** [comment]
I'm adding an option to call a command after the compare, so I'll test that change as well. Thanks!
