### ISSUE TITLE
Add option to prompt when file changes on disk, irrespective of conflicts

### ISSUE THREAD

**Issue by DanielJoyce** [lwblackledge/file-watcher#2]
1) Install file watcher
2) Open file in atom, make no edits
3) Open file in VI, and edit
4) Atom reloads file without prompting

File watcher only seems to prompt if atom file has unsaved edits.

Other editors will prompt whenever the file changes, even with no pending edits

**Comment by lwblackledge** [comment]
Thanks @DanielJoyce 
Unfortunately what you are talking about is the default functionality in Atom.
The `file-watcher` package is triggered by the conflict state from Atom's internal file tracking, and that is not fired in the scenario you describe.

I did a quick check on editor behaviour:

| Editor | Behavior |
| --- | --- |
| Atom | Automatically reloads |
| VS Code | Automatically reloads |
| Notepad++ | Prompts to reload |
| WebStorm | Automatically reloads |

It looks like this might be a personal preference thing by the creators of each editor. I will look into this as an optional addition to `file-watcher` but I do not know if I can intercept the base Atom behaviour.

**Comment by zessin** [comment]
+1 for this feature.
Imagine you're analysing a log file from a running application that updates this log file. Auto reloading the log file is awful!
As far as I know, the default behaviour on Atom is to auto reload the file, and there is no option to set it to prompt you for a confirmation to reload.

IMO, it would be nice having a way to get a prompt confirmation for reloading the file (no matter if it has changes or not).

**Comment by lwblackledge** [comment]
I have been looking into this and it might require an update to TextBuffer since it does not expose the event that the file on disk has changed unless there is a conflict.

**Comment by lwblackledge** [comment]
Resolved by 52bb9c0a56f6968424c6b928dd8e6d941afa6dfc

I added an option (off by default) to `file-watcher` where it will intercept file change events before `text-buffer` reloads. It does this by faking out the conflict status. 

I had to re-register the `text-buffer` file events due to an order of operation issue, but it does work for now.

If this is a feature you want please make sure you check the option in settings.

I'm closing this issue for now but I'll re-open it if this solution is inconsistent.

Thanks!

**Comment by farvardin** [comment]
Thanks a lot for adding this important feature!! (It's also working this way with the Kate, Geany, gvim and Scite text editors, maybe it's more common to have this with Unix / Linux editors). I hope next releases of Atom won't break this option.
