### ISSUE TITLE
Ask only once

### ISSUE THREAD

**Issue by itavero** [lwblackledge/file-watcher#20]
It would be nice if instead of notifying me for each change, I would have the option the ignore all future changes to a file and only view the current state.
This is especially useful for log files that are still active.

**Comment by lwblackledge** [comment]
Ah this is a nice idea. Maybe I can add it to the conflict as 'ignore all future changes' and just dispose. Changes will be ignored until you next open the file.

**Comment by lwblackledge** [comment]
1.1.0 release should include the Ignore All option now.

**Comment by itavero** [comment]
Thanks for implementing this so fast, @lwblackledge!
