### ISSUE TITLE
Changing Branchs

### ISSUE THREAD

**Issue by marcel0ll** [lwblackledge/file-watcher#22]
When I change branchs I get annoyed by the reload popup. 
Isn't there a way to check if the branch has been changed and not ask for reloading?

**Comment by lwblackledge** [comment]
That would be a decent sized change but I'll think about how I could disable it on git change.

However, that might cause some other unintended issues if you have unsaved changes and switch branches.

You could disable the prompt on change option, which will only show the prompt if you have a modified buffer?

**Comment by marcel0ll** [comment]
If you have unsaved changes that would cause conflict git doesn't allow you to change branchs as far as I know.

**Comment by lwblackledge** [comment]
I tested with the option 'Prompt on Change' disabled and I think this is what you want. It will not prompt between branches unless you have a modified buffer in Atom.

![image](https://cloud.githubusercontent.com/assets/1142220/24025705/78c00a3c-0a92-11e7-9403-b60239168332.png)

Is that what you were looking for?
