### ISSUE TITLE
No prompt when using filezilla

### ISSUE THREAD

**Issue by franckv6r** [lwblackledge/file-watcher#25]
Hello
i'm using atom with filezilla. But when file change on disk, no prompt message to warn me.
Steps to reproduce :
1. load a file in filezilla (a log file for example from your ftp) and open it with atom.
2. Make changes on your website to generate some logs.
3. Reload the file from filezilla
4. Atom display the file with the blue dot on the tab (of file name) but file watcher doesn't prompt anything.
Need to close the file without saving and re-open it so see the changes on my log file.

**Comment by borishere** [comment]
@franckv6r  Hi.
I have the same issue #26. I find it impossible to work with this bug. @lwblackledge can you clarify this situation?

**Comment by lwblackledge** [comment]
@franckv6r and @borishere - can you try with the `Use WatchFile` option enabled? I think filezilla is not triggering `inotify` events.

If that option is already enabled please let me know.

**Comment by borishere** [comment]
My issue #26 seems to be solved.

**Comment by lwblackledge** [comment]
Very delayed but the latest update should help - if you're still using Atom
