### ISSUE TITLE
Is there a way to make it work with PyCharm 'safe write'?

### ISSUE THREAD

**Issue by kiwi0fruit** [lwblackledge/file-watcher#28]
This is a feature request not a bug report.

File Watcher fails to simultaineously work with PyCharm. Seems like PyCharm first renames the original file (appends `__jb_old__`) then writes modified file as new file with old unmodified name.  So the file in Atom only changes it's name (name  + `__jb_old__`).

I need this feature to write code in PyCharm and to execute via Atom-Hydrogen-Jupyter.

**PS**

Though Notepad++ works with PyCharm flawlessly.

**UPD**
This is actually a [PyCharm "safe write" function](https://stackoverflow.com/questions/23864827/jb-bak-and-jb-old-files-in-pycharm). If disable it then everything works OK. But still PyCharm (and other JetBrains software) support may be a good feature.

**Comment by lwblackledge** [comment]
Hi @kiwi0fruit, this was actually raised as part of #14. You found the workaround I offered, but the naming change is not something that I will be adding to this plugin.
