### ISSUE TITLE
Uncaught (in promise) Error: Invalid encoding name: windows1252

### ISSUE THREAD

**Issue by plugato** [lwblackledge/file-watcher#31]
not working from encoding windows1252
Uncaught (in promise) Error: Invalid encoding name: windows1252

**Comment by plugato** [comment]
i'am change atom.workspace.getActiveTextEditor().setEncoding("utf8") 
and after compare change
atom.workspace.getActiveTextEditor().setEncoding("windows1252")

**Comment by lwblackledge** [comment]
New version should help - there have been some updates to Atom that I needed to accommodate
