### ISSUE TITLE
Prompt on change does not work on nfs files changed outside Atom

### ISSUE THREAD

**Issue by mirela-rabulea** [lwblackledge/file-watcher#33]
Hi,
I have Ubuntu 16.04.3 LTS, and I installed recently the latest file-wacher from Atom packages.
I have a file on a NFS mount, which I change outside of Atom. Atom reloads it automatically without prompting there was a change.
I have checked the "Prompt on change" check-box in settings.
I also checked "Use WatchFile --RELOAD REQUIRED", since my file is on a mounted file system.

Regards,
Mirela

**Comment by lwblackledge** [comment]
New version should help - there have been some updates to Atom that I needed to accommodate
