### ISSUE TITLE
Not prompting on change and reloading automatically even with option turned off.

### ISSUE THREAD

**Issue by raphaelmsx** [lwblackledge/file-watcher#34]
Hi, just installed Atom and file-watcher on Fedora 28 KDE.

If I have an open file on Atom and on another editor, any change made outside is automatically loaded on Atom without any prompt, even with the setting "Reload Automatically" turned off.

I have tried with settings "Use WatchFile" and "Include the Compare option" turned on an off, to no avail.

Thanks.

**Comment by raphaelmsx** [comment]
Oh, I forgot to mention: the file is located on /home/user, it's a local xfs filesystem.

**Comment by lwblackledge** [comment]
Thanks, this was a very stale project but since a few people are reporting issues I'll look into it. Perhaps this is broken after recent Atom updates.

**Comment by raphaelmsx** [comment]
For now I'm using other editor just because of this bug, it's really necessary for me this feature when editing files. How can I keep track when it gets fixed, here on this topic or where?

**Comment by lwblackledge** [comment]
New version should help - there have been some updates to Atom that I needed to accommodate
