### ISSUE TITLE
file-watcher is completely inconsistent

### ISSUE THREAD

**Issue by pingpong2011** [lwblackledge/file-watcher#36]
This bug is repeating a few things in other watch posts, but I wanted to collect my bugs here:

1) If Atom is not in focus, it does no reloading

2) It always automatically reloads if there's no edits in Atom

3) It never reloads if there are edits in Atom

Version: Atom 1.29.0 x64 Windows

I have "Prompt on Change" and "Include the compare option" checked. "Reload Automatically" is UNCHECKED but the settings are completely disregarded.

I tried with the "Use Watchfile" on - it sort of worked, but inconsistently. It will work _once_, but then if I reload as instructed it goes back to the broken behavior. Even if it is ON and I turn it OFF without reloading, I get asked properly.

It looks likes initialization just doesn't apply the options at all, and defaults to reloading automatically if there's no edits.

**Comment by lwblackledge** [comment]
Thanks, it's been a while since I looked at this as I have stopped using Atom, but I'll see what I can do to get these resolved.

By the way, are you using a mounted filesystem? Atom uses node fs which relies on the inotify feature, and mounted filesystems don't always emit those events.

**Comment by lwblackledge** [comment]
Similar to #33 & #34

**Comment by ericseppanen** [comment]
What is "a mounted filesystem" supposed to mean?  Every filesystem that's in use is "mounted".

If there's some particular requirement that some filesystems support but others don't, then maybe you could clarify what that requirement is?

**Comment by lwblackledge** [comment]
New version should help - there have been some updates to Atom that I needed to accommodate. Docs updated to specify that WatchFile should be used on file systems like SSHFS
