### ISSUE TITLE
Additional diff option

### ISSUE THREAD

**Issue by fractalf** [lwblackledge/file-watcher#6]
Would it be possible to add a setting so one could use a different differ?
ie "split-diff"

**Comment by lwblackledge** [comment]
I am having a lot of trouble getting win-sshfs working on Windows 10 (I do not have Win7, but may try it on a VM).

As for split-diff, I currently do not have an option for that but split-diff looks like it could run as a post compare hook, so I am going to modify this just for the split-diff enhancement and roll your win-sshfs into #5.

**Comment by lwblackledge** [comment]
I'm waiting on a PR for split-diff since it is broken on Windows for me.

Until then, trying to send commands should work, but doesn't. I'll check some other packages and see if there is a solution.
