### ISSUE TITLE
Doesn't work for files stored in the root directory of the disk (Atom 1.4.3 on Windows 10 Pro x86)

### ISSUE THREAD

**Issue by mrysbekov** [lwblackledge/file-watcher#7]
I have a fresh Atom setup (v1.4.3) on Windows 10 Pro (x86), with the "file-watcher" package installed. "Include the Compare" and "Prompt on Change" options are enabled. I create a file in Atom, put some contents in it, and save it to "D:\123.txt". I then open this file in another text editor, add more contents to it, and save it. I then switch back to Atom (which i didn't close, and inside which I still have the "D:\123.txt" file open) and there is no prompt of any kind informing me that the file has changed on disk.

**Comment by mrysbekov** [comment]
Follow-up: 

If I save the file to "D:\Subfolder\123.txt" instead of just "D:\123.txt", file-watcher works as expected.

**Comment by lwblackledge** [comment]
Thanks, very interesting. I am not sure why this would be the case, but I'll take a look. Incidentally, the default atom behavior does not work when the file is at the root either, so it may be something in the lower filesystem code in text-buffer.

**Comment by lwblackledge** [comment]
Okay, it seems to be an issue in node-pathwatcher, which is used by text-buffer, which is used by file-watcher. I'll raise an issue in node-pathwatcher and see what they do, since this is not something I can fix easily.

**Comment by lwblackledge** [comment]
Raised https://github.com/atom/node-pathwatcher/issues/102 with PR
